CREATE TABLE `rdv` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` TINYTEXT NULL,
	`rdv_date` DATE NULL DEFAULT NULL,
	`rdv_hour` TEXT NULL,
	`date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
)